settings:
  title: 'Digitizer Status Page'
  url: 'https://webs.digitizer.link' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: digitizer # unique identifier
    name: digitizer.co.il
    # description: 'https://www.digitizer.co.il' # default=empty
    url: 'https://www.digitizer.co.il' # URL to fetch
    # method: GET # default=GET
    # expectStatus: 200 # operational status, default=200
    # followRedirect: false # should fetch follow redirects, default=false
    # linkable: false # allows the title to be a link, default=true

  - id: hempishop
    name: hempishop.co.il
    # description: 'https://www.hempishop.co.il'
    url: 'https://www.hempishop.co.il'
    # method: GET
    # expectStatus: 200
    # linkable: false # allows the title to be a link, default=true

  - id: maxdrawz
    name: maxdrawz.com
    url: 'https://maxdrawz.com'
    # method: GET
    # expectStatus: 200
    # linkable: false 

  - id: thecryptotips
    name: thecrypto.tips
    url: 'https://www.thecrypto.tips'

  - id: langos
    name: langos.co.il
    url: 'https://www.langos.co.il'

  - id: time-machine
    name: time-machine.co.il
    url: 'https://www.time-machine.co.il'
    
